### ISSUE TITLE
CREATE TABLE %string{table_name} results in an error

### ISSUE THREAD

**Issue by mudrz** [roddyyaga/ppx_rapper#15]
When creating a table, this works:
```ocaml
    [%rapper execute {sql| CREATE TABLE my_table ( ... ) |sql}]
```
but this:
```ocaml
    let table_name = "my_table"
    [%rapper execute {sql| CREATE TABLE %string{table_name} ( ... ) |sql}] ~table_name
```
results in
```
Fatal error: exception Error in ppx_rapper: Syntax error in SQL: 'syntax error at or near "?"'
```
is this expected or my syntax is wrong?

**Comment by roddyyaga** [comment]
The way ppx_rapper works is that input parameters (`%type{...}`) are converted into the SQL parameter `?`. These can only be used for things that are parameters from a SQL perspective, which table names are not.

I think using Caqti directly is probably the easiest way to get queries parametrised in this way (see [here](https://paurkedal.github.io/ocaml-caqti/caqti/Caqti_request/index.html#convenience)). Support for this could be added to ppx_rapper (e.g. a syntax like `[%rapper execute {sql| CREATE TABLE %static{} (); |sql} table_name]` but I don't have plans to do so any time soon (PR's are always welcome though!)
