### ISSUE TITLE
insert multiple values

### ISSUE THREAD

**Issue by mudrz** [roddyyaga/ppx_rapper#16]
I'm trying to insert multiple values in a table

Inserting a single value works:
```ocaml
type my_thing = { a: int; b: string }
let insert_my_thing = [%rapper execute {sql|
  INSERT INTO my_things (a, b)
  VALUES (%int{a}, %string{b});
|sql} record_in]

(*
my_thing ->
(module Caqti_lwt.CONNECTION) ->
(unit, [> Caqti_error.call_or_retrieve ]) result Lwt.t
*)
```

but I can't get how to use the list syntax to insert `my_thing list`:
```ocaml
type my_thing = { a: int; b: string }
let insert_my_thing = [%rapper execute {sql|
  INSERT INTO my_things (a, b)
  VALUES %list{(%int{a}, %string{b})};
|sql} record_in]
```

```
Fatal error: exception "Assert_failure ppx/ppx_rapper.ml:51:6"
```

**Comment by roddyyaga** [comment]
Currently using more than one parameter with the `%list` syntax isn't supported (I am changing the error message for this to be more informative).

I would probably try constructing the Caqti query for this case manually (you can check the code ppx_rapper generates for `%list` by looking at the function `list` in test.expected.ml). You could also try using a [custom encoder](https://github.com/roddyyaga/ppx_rapper#custom-types) that encodes the record in the right way, but then you are building the SQL query yourself by combining strings which is sad.
