### ISSUE TITLE
more examples of connection creation, please!

### ISSUE THREAD

**Issue by phstrauss** [roddyyaga/ppx_rapper#23]
Hello! My first encounter with Lwt is by using ppx_rapper_lwt (even first encounter with a monadic pattern to conform to) and I lack something which will probably looks trivial to you: a connection (db handler) creation and use example! a non pooled one, because I'm using sqlite3. I know, I know, shame on me, I'm an eternal beginner with ocaml.

Also, is the Db handler always a whole module or is there a lighter alternative?

Thank U!

**Comment by roddyyaga** [comment]
Hi, I've added an example of that to [the examples](https://github.com/roddyyaga/ppx_rapper/blob/master/examples/lwt/examples_lwt.ml#L142). The connection is a caqti thing, not ppx_rapper, so you'll probably find [the caqti docs](https://github.com/paurkedal/ocaml-caqti) more useful.
