### ISSUE TITLE
escaping of ocaml keywords in record_out

### ISSUE THREAD

**Issue by joprice** [roddyyaga/ppx_rapper#41]
Is there a way to create a query that relies on a column name identical to an ocaml keyword, such as `type`? I tried both of the typical conventions of type_ and _type, but they are passed through to the query. Or is there perhaps a way to alias a field when using `record_out`, having the struct's field differ from the table's?

**Comment by joprice** [comment]
I should also mention this could be worked around with a subquery that renames the fields, but this can become cumbersome.

**Comment by anmonteiro** [comment]
I think this is easy to do with `AS`, e.g. `SELECT type as @string{type_}`
