### ISSUE TITLE
MariaDB/SQLite support

### ISSUE THREAD

**Issue by apeschar** [roddyyaga/ppx_rapper#6]
Although the README states that ppx_rapper is intended for use with PostgreSQL, it actually seems to work fine with MariaDB.  Queries that are not also valid PostgreSQL syntax (mainly INSERT ... SET ...) need `syntax_off`, but that seems to be it.

Perhaps that should be documented?  I'm willing to submit a PR for that, I just wanted to know if you have any thoughts on this, or whether I'm missing something that would make this library not (yet) useful with MariaDB.

**Comment by roddyyaga** [comment]
Thanks, good point. I can't see why there would be any issues with using other SQL dialects that Caqti supports. I've updated the README to that effect.
