### ISSUE TITLE
Support all request processing functions

### ISSUE THREAD

**Issue by Lelio-Brun** [roddyyaga/ppx_rapper#8]
Hi, thanks for the work!
The ppx only allows bindings to `exec`, `find`, `find_opt` and `collect_list`. Are there plans to also support `fold`, `fold_s` and `iter_s` (and `rev_collect_list` for the sake of completeness), or were they omitted on purpose?

**Comment by roddyyaga** [comment]
Hey, I'm not planning on implementing those (unless I encounter some case where they are needed for performance reasons), but happy to accept a PR adding them.
