### ISSUE TITLE
Async 

### ISSUE THREAD

**Issue by bikallem** [roddyyaga/ppx_rapper#9]
Hi,

Thanks for the nice library. Are you open to make this ppx/library compatible with `async` library in addition to `lwt`? It probably needs to be split into two packages, `ppx_rapper-lwt` and `ppx_rapper.async` ?

**Comment by roddyyaga** [comment]
Hey, I'd definitely be open to a PR to do that but probably won't get round to adding it myself in the near future.

**Comment by bikallem** [comment]
Thanks. I should be able to able to open a PR to implement this soonish.

**Comment by bikallem** [comment]
PR opened https://github.com/roddyyaga/ppx_rapper/pull/10

**Comment by bikallem** [comment]
Fixed by #10. Closing.
